### ISSUE TITLE
ircfmt: Strip eats escaped colour

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [goshuirc/irc-go#13]
`ircfmt.Strip()` internally converts `\x03` to `$c`, and uses it while stripping out colours. This means that if you pass the string `test $c of stripping`, you get the result `test  of stripping`, as the literal `$c` is removed from the string as a part of the strip process.

**Comment by DanielOaks** [comment]
Dodgy, it shouldn't be doing that at all. Thanks for finding the issue!
