### ISSUE TITLE
ParseUserhost sets the User of a UserHost the passed string when the string is not a mask

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [goshuirc/irc-go#22]
When calling ParseUserhost, for example, with "test", the resulting UserHost struct looks like this: `UserHost{Nick: "", User: "test", Host: ""}`. The parser tests have no checks for this, but [RFC 1459](https://tools.ietf.org/html/rfc1459#section-2.3.1) (see note 6) states that in this case the mask is just a nick.

**Comment by slingamn** [comment]
This is now #57
